---
kind: pipeline
name: test

trigger:
  event:
  - push
  - pull_request
  - tag

platform:
  os: linux
  arch: amd64

steps:
- name: test
  pull: default
  image: node:10
  commands:
  - scripts/ci

node:
  instance: agent-amd64

---
kind: pipeline
name: build-embedded

depends_on:
- test

trigger:
  ref:
  - "refs/heads/master"
  - "refs/heads/*-dev"
  - "refs/heads/release-*"
  event:
  - push

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: default
  image: node:10
  commands:
  - ./scripts/build-embedded

- name: upload
  pull: default
  image: plugins/s3
  settings:
    bucket: rancheredge-ui
    region: ap-east-1
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    source: dist/${DRONE_BRANCH}.tar.gz
    target: /ui

node:
  instance: agent-amd64

---
kind: pipeline
name: build-embedded-tag

depends_on:
- test

trigger:
  event:
  - tag

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: default
  image: node:10
  commands:
  - ./scripts/build-embedded

- name: upload
  pull: default
  image: plugins/s3
  settings:
    bucket: rancheredge-ui
    region: ap-east-1
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    source: dist/${DRONE_TAG}.tar.gz
    target: /ui

node:
  instance: agent-amd64

---
kind: pipeline
name: hosted-master

depends_on:
- test

trigger:
  ref:
  - "refs/heads/master"
  event:
  - push

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: default
  image: node:10
  commands:
  - ./scripts/build-hosted

- name: upload
  pull: default
  image: plugins/s3
  settings:
    bucket: rancheredge-ui
    region: ap-east-1
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    source: dist/latest/**/*
    strip_prefix: dist/latest/
    target: /ui/latest

node:
  instance: agent-amd64

---
kind: pipeline
name: hosted-branch

depends_on:
- test

trigger:
  ref:
  - "refs/heads/*-dev"
  - "refs/heads/release-*"
  event:
  - push

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: default
  image: node:10
  commands:
  - ./scripts/build-hosted

- name: upload
  pull: default
  image: plugins/s3
  settings:
    bucket: rancheredge-ui
    region: ap-east-1
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    source: dist/${DRONE_BRANCH}/**/*
    strip_prefix: dist/${DRONE_BRANCH}/
    target: /ui/${DRONE_BRANCH}

node:
  instance: agent-amd64

---
kind: pipeline
name: hosted-tag

depends_on:
- test

trigger:
  event:
  - tag

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: default
  image: node:10
  commands:
  - ./scripts/build-hosted

- name: upload
  pull: default
  image: plugins/s3
  settings:
    bucket: rancheredge-ui
    region: ap-east-1
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    source: dist/${DRONE_TAG}/**/*
    strip_prefix: dist/${DRONE_TAG}/
    target: /ui/${DRONE_TAG}

node:
  instance: agent-amd64
