apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: my-mqtt #可配置，应用名称
  namespace: kube-system #固定使用kube-system
spec:
  chart: emqx # 固定的app name应用名称
  repo: http://charts.cnrancher.cn #固定，使用catalog url地址
  version: v1.0.0-rc.1 #可配置，模板版本 - (可升级)
  targetNamespace: default #可配置，命名空间 - (可升级)
  valuesContent: |- # 可配置参数，YAML模板参数 - (可升级)
    replicaCount: 3
    image:
      pullPolicy: IfNotPresent
      repository: emqx/emqx
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 512Mi
    persistence:
      accessMode: ReadWriteOnce
      enabled: false
      size: 20Mi
    service.type: ClusterIP
    emqxConfig:
      EMQX_CLUSTER__K8S__ADDRESS_TYPE: hostname
      EMQX_CLUSTER__K8S__APISERVER: https://kubernetes.default.svc:443
      EMQX_CLUSTER__K8S__SUFFIX: svc.cluster.local
    emqxLicneseSecretName: null
    tolerations: []
    nodeSelector: {}
    affinity: {}
    ingress:
      annotations: {}
      enabled: false
      hosts:
      - chart-example.local
      path: /
      tls: []
